name: Virtual Audio Driver Building

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Check Chocolatey installation
        run: choco --version

      - name: Install Visual Studio 2022 dependencies
        run: |
          choco install visualstudio2022-workload-manageddesktop -y
          if ($LASTEXITCODE -ne 0) { exit 1 }
          
          choco install visualstudio2022-workload-nativedesktop -y
          if ($LASTEXITCODE -ne 0) { exit 1 }
          
          choco install visualstudio2022-workload-vctools -y
          if ($LASTEXITCODE -ne 0) { exit 1 }
          
          choco install windowsdriverkit11 -y
          if ($LASTEXITCODE -ne 0) { exit 1 }

      # Create MSBuild properties file to disable INF verification and API validation
      - name: Create MSBuild properties
        run: |
          $propsContent = @"
<Project>
  <PropertyGroup>
    <!-- Disable INF verification -->
    <DisableInfVerifier>true</DisableInfVerifier>
    <SkipInf>true</SkipInf>
    <!-- Disable API validation -->
    <ValidateDriverApiCompatibility>false</ValidateDriverApiCompatibility>
  </PropertyGroup>
</Project>
"@
          Set-Content -Path "DisableVerification.props" -Value $propsContent
          Write-Host "Created MSBuild properties file to disable verification steps"

      # Build with verification steps disabled
      - name: Build the driver
        run: |
          msbuild "VirtualAudioDriver.sln" /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:ForceImportBeforeCppTargets="$PWD\DisableVerification.props"

      # Find the actual driver files
      - name: Locate driver files
        id: locate_files
        run: |
          # Find .sys file
          $sysFiles = Get-ChildItem -Path . -Recurse -Filter "VirtualAudioDriver.sys" | Where-Object { $_.FullName -like "*\${{ matrix.platform }}\${{ matrix.configuration }}*" }
          
          if ($sysFiles.Count -gt 0) {
            $sysFile = $sysFiles[0].FullName
            $sysDir = Split-Path -Parent $sysFile
            
            Write-Host "Found driver at: $sysFile"
            Write-Host "Driver directory: $sysDir"
            
            echo "DRIVER_DIR=$sysDir" >> $env:GITHUB_ENV
          } else {
            Write-Warning "Could not find VirtualAudioDriver.sys file!"
            # List directories to help debug
            Write-Host "Searching directories:"
            Get-ChildItem -Path . -Directory -Recurse | Where-Object { $_.Name -eq "${{ matrix.platform }}" } | ForEach-Object {
              Write-Host $_.FullName
              Get-ChildItem -Path $_.FullName -Directory | ForEach-Object {
                Write-Host "  $_"
                if ($_.Name -eq "${{ matrix.configuration }}") {
                  Write-Host "    Files:"
                  Get-ChildItem -Path $_.FullName | ForEach-Object {
                    Write-Host "      $_"
                  }
                }
              }
            }
          }

      - name: List build directory
        run: |
          if (Test-Path env:DRIVER_DIR) {
            Write-Host "Contents of driver directory:"
            dir "${{ env.DRIVER_DIR }}"
          } else {
            Write-Host "Searching for any built files:"
            Get-ChildItem -Path . -Recurse -Include "*.sys","*.inf" | ForEach-Object {
              Write-Host $_.FullName
            }
          }

      - name: Upload built driver
        id: upload_artifact
        if: env.DRIVER_DIR != ''
        uses: actions/upload-artifact@v4
        with:
          name: Built-Driver-${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            ${{ env.DRIVER_DIR }}\VirtualAudioDriver.sys
            ${{ env.DRIVER_DIR }}\VirtualAudioDriver.inf

      # Fallback upload if specific files weren't found
      - name: Fallback upload
        if: env.DRIVER_DIR == ''
        uses: actions/upload-artifact@v4
        with:
          name: Built-Files-${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            **\${{ matrix.platform }}\${{ matrix.configuration }}\**\*.sys
            **\${{ matrix.platform }}\${{ matrix.configuration }}\**\*.inf

      - name: Generate release tag
        id: generate_tag
        run: |
          $releaseTag = (Get-Date).ToString('yy.MM.dd')
          echo "RELEASE_TAG=$releaseTag" >> $env:GITHUB_ENV

      - name: Show generated release tag
        run: |
          echo "Generated Release Tag: ${{ env.RELEASE_TAG }}"